# -*- coding: utf-8 -*-

# Kanji Coach for Anki
# Copyright (C) 2017-Present  Dorian DAUDIER
#
# This module implements functions designed to generate custom kanji learning
# order based on their order of appearance in a user input text.

def isKanji(c):
    """Tests whether a character is a Kanji or not.
    It returns boolean True if the character is a Kanji, false if not)"""
    pass

def generate_list(string):
    """Returns a list of unique Kanji characters contained in a text string.
    The Kanji are ordered by their first occurence in the text."""
    pass

def generate_to_file(string, filename):
    """Writes the custom list of Kanji generated by order of appearance from a
    string, in the file provided in the arguments."""
    pass
